[package]
name = "neals"
version = "0.2.1"
edition = "2021"

[[bin]]
name = "neals"
path = "src/main.rs"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "cargo", "color"] }
clap_complete = { version = "4.6.8", features = ["unstable-dynamic"] }
comfy-table = "7"
crossterm = "0.29.0"
neals-common = { path = "../common" }
owo-colors = "4.3.0"
ratatui = "0.30.2"
