use crate::style;
use anyhow::{bail, Context, Result};
use neals_common::{ensure_dir, state_dir};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, ExitStatus, Stdio};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ShellKind {
    Bash,
    Zsh,
    Other,
}

pub fn enter_project_shell(project: &str, path: &Path) -> Result<ExitCode> {
    let kind = detect_shell();
    let shell_path = shell_executable();

    match kind {
        ShellKind::Bash => {
            let rc = write_bash_rc(project)?;
            // devenv: `shell [CMD] [ARGS]...` — do NOT pass a bare `--` (it becomes CMD).
            run_devenv(
                path,
                project,
                &[
                    "--quiet",
                    "shell",
                    &shell_path,
                    "-i",
                    "--rcfile",
                    rc.to_str().context("rc path not utf-8")?,
                ],
            )
        }
        ShellKind::Zsh => {
            let zdot = write_zsh_dir(project)?;
            let status = Command::new("devenv")
                .args(["--quiet", "shell", &shell_path, "-i"])
                .current_dir(path)
                .env("ZDOTDIR", &zdot)
                .env("NEALS_PROJECT", project)
                .stdin(Stdio::inherit())
                .stdout(Stdio::inherit())
                .stderr(Stdio::inherit())
                .status()
                .context("failed to run `devenv` (is it installed and on PATH?)")?;
            Ok(exit_code_from_status(status))
        }
        ShellKind::Other => {
            style::print_warn(&format!(
                "branded prompt not configured for `{}`",
                shell_path
            ));
            run_devenv(path, project, &["--quiet", "shell", &shell_path, "-i"])
        }
    }
}

pub fn run_project_exec(project: &str, path: &Path, command: &[String]) -> Result<ExitCode> {
    if command.is_empty() {
        bail!("no command provided");
    }
    let mut args: Vec<&str> = vec!["--quiet", "shell"];
    args.extend(command.iter().map(String::as_str));
    run_devenv(path, project, &args)
}

fn detect_shell() -> ShellKind {
    let name = shell_executable();
    let base = Path::new(&name)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("bash");
    match base {
        "bash" => ShellKind::Bash,
        "zsh" => ShellKind::Zsh,
        _ => ShellKind::Other,
    }
}

fn shell_executable() -> String {
    env::var("SHELL").unwrap_or_else(|_| "bash".into())
}

fn write_bash_rc(project: &str) -> Result<PathBuf> {
    let dir = state_dir()?;
    ensure_dir(&dir)?;
    let path = dir.join(format!("bashrc-{project}"));
    let home = env::var("HOME").unwrap_or_default();
    let content = format!(
        r#"# generated by neals — do not edit
if [ -f "{home}/.bashrc" ]; then
  # shellcheck disable=SC1091
  . "{home}/.bashrc"
fi
export NEALS_PROJECT="{project}"
if [ -t 1 ] && [ -z "${{NO_COLOR:-}}" ]; then
  PS1='\[\e[35m\]neals:{project}\[\e[0m\] \w \$ '
else
  PS1='neals:{project} \w \$ '
fi
"#
    );
    fs::write(&path, content).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(path)
}

fn write_zsh_dir(project: &str) -> Result<PathBuf> {
    let dir = state_dir()?.join(format!("zsh-{project}"));
    ensure_dir(&dir)?;
    let home = env::var("HOME").unwrap_or_default();
    let content = format!(
        r#"# generated by neals — do not edit
if [ -f "{home}/.zshrc" ]; then
  source "{home}/.zshrc"
fi
export NEALS_PROJECT="{project}"
if [[ -o interactive ]] && [[ -z "${{NO_COLOR:-}}" ]]; then
  PROMPT="%F{{magenta}}neals:{project}%f %~ %# "
else
  PROMPT="neals:{project} %~ %# "
fi
"#
    );
    let zshrc = dir.join(".zshrc");
    fs::write(&zshrc, content).with_context(|| format!("failed to write {}", zshrc.display()))?;
    Ok(dir)
}

fn run_devenv(dir: &Path, project: &str, args: &[&str]) -> Result<ExitCode> {
    let status = Command::new("devenv")
        .args(args)
        .current_dir(dir)
        .env("NEALS_PROJECT", project)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .status()
        .context("failed to run `devenv` (is it installed and on PATH?)")?;
    Ok(exit_code_from_status(status))
}

fn exit_code_from_status(status: ExitStatus) -> ExitCode {
    match status.code() {
        Some(0) => ExitCode::SUCCESS,
        Some(code) => ExitCode::from(u8::try_from(code).unwrap_or(1)),
        None => ExitCode::FAILURE,
    }
}
