use crate::daemon_client::with_daemon;
use crate::style;
use anyhow::{bail, Context, Result};
use neals_common::{ensure_dir, state_dir, Request, Response};
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{Command, ExitCode, ExitStatus, Stdio};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
enum ShellKind {
    Bash,
    Zsh,
    Other,
}

pub fn enter_project_shell(project: &str, path: &Path) -> Result<ExitCode> {
    let netns_pid = require_netns_pid(project)?;
    let kind = detect_shell();
    let shell_path = shell_executable();

    match kind {
        ShellKind::Bash => {
            let rc = write_bash_rc(project)?;
            // devenv shell: bare `--` becomes CMD — omit it.
            run_in_netns(
                path,
                project,
                netns_pid,
                &[
                    "--quiet",
                    "shell",
                    &shell_path,
                    "-i",
                    "--rcfile",
                    rc.to_str().context("rc path not utf-8")?,
                ],
            )
        }
        ShellKind::Zsh => {
            let zdot = write_zsh_dir(project)?;
            let status = nsenter_devenv(
                path,
                project,
                netns_pid,
                &["--quiet", "shell", &shell_path, "-i"],
                &[("ZDOTDIR", zdot.as_os_str())],
            )?;
            Ok(exit_code_from_status(status))
        }
        ShellKind::Other => {
            style::print_warn(&format!(
                "branded prompt not configured for `{}`",
                shell_path
            ));
            run_in_netns(
                path,
                project,
                netns_pid,
                &["--quiet", "shell", &shell_path, "-i"],
            )
        }
    }
}

pub fn run_project_exec(project: &str, path: &Path, command: &[String]) -> Result<ExitCode> {
    if command.is_empty() {
        bail!("no command provided");
    }
    let netns_pid = require_netns_pid(project)?;
    // devenv 2.x drops flag-looking args of `shell CMD …` on the floor (`bash -c '…'`
    // silently runs nothing), so drive a plain non-interactive bash over stdin.
    let script = command
        .iter()
        .map(|arg| neals_common::shell_quote(arg))
        .collect::<Vec<_>>()
        .join(" ");
    let status = nsenter_devenv_stdin(
        path,
        project,
        netns_pid,
        &["--quiet", "shell", "bash"],
        &format!("{script}\n"),
    )?;
    Ok(exit_code_from_status(status))
}

fn require_netns_pid(project: &str) -> Result<u32> {
    match with_daemon(Request::Status)? {
        Response::Status { projects } => {
            let Some(p) = projects.iter().find(|p| p.name == project) else {
                bail!("project `{project}` is not running; start it with `neals up {project}`");
            };
            if p.netns_pid == 0 {
                bail!("project `{project}` has no netns pid (daemon too old?)");
            }
            Ok(p.netns_pid)
        }
        Response::Error { message } => bail!(message),
        _ => bail!("unexpected daemon response for Status"),
    }
}

fn detect_shell() -> ShellKind {
    let name = shell_executable();
    let base = Path::new(&name)
        .file_name()
        .and_then(|s| s.to_str())
        .unwrap_or("bash");
    match base {
        "bash" => ShellKind::Bash,
        "zsh" => ShellKind::Zsh,
        _ => ShellKind::Other,
    }
}

fn shell_executable() -> String {
    env::var("SHELL").unwrap_or_else(|_| "bash".into())
}

fn write_bash_rc(project: &str) -> Result<PathBuf> {
    let dir = state_dir()?;
    ensure_dir(&dir)?;
    let path = dir.join(format!("bashrc-{project}"));
    let home = env::var("HOME").unwrap_or_default();
    let content = format!(
        r#"# generated by neals — do not edit
if [ -f "{home}/.bashrc" ]; then
  # shellcheck disable=SC1091
  . "{home}/.bashrc"
fi
export NEALS_PROJECT="{project}"
if [ -t 1 ] && [ -z "${{NO_COLOR:-}}" ]; then
  PS1='\[\e[35m\]neals:{project}\[\e[0m\] \w \$ '
else
  PS1='neals:{project} \w \$ '
fi
"#
    );
    fs::write(&path, content).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(path)
}

fn write_zsh_dir(project: &str) -> Result<PathBuf> {
    let dir = state_dir()?.join(format!("zsh-{project}"));
    ensure_dir(&dir)?;
    let home = env::var("HOME").unwrap_or_default();
    let content = format!(
        r#"# generated by neals — do not edit
if [ -f "{home}/.zshrc" ]; then
  source "{home}/.zshrc"
fi
export NEALS_PROJECT="{project}"
if [[ -o interactive ]] && [[ -z "${{NO_COLOR:-}}" ]]; then
  PROMPT="%F{{magenta}}neals:{project}%f %~ %# "
else
  PROMPT="neals:{project} %~ %# "
fi
"#
    );
    let zshrc = dir.join(".zshrc");
    fs::write(&zshrc, content).with_context(|| format!("failed to write {}", zshrc.display()))?;
    Ok(dir)
}

fn run_in_netns(dir: &Path, project: &str, netns_pid: u32, args: &[&str]) -> Result<ExitCode> {
    let status = nsenter_devenv(dir, project, netns_pid, args, &[])?;
    Ok(exit_code_from_status(status))
}

/// nsenter + devenv with the stdio wiring left to the caller.
fn nsenter_command(dir: &Path, project: &str, netns_pid: u32) -> Command {
    let mut cmd = Command::new("nsenter");
    cmd.args([
        "--user",
        "--net",
        "--mount",
        "--preserve-credentials",
        "-t",
        &netns_pid.to_string(),
        // nsenter drops cwd to `/` across the mount-ns switch; re-enter the
        // project dir inside the guest (`--dev-bind / /` keeps the path valid).
        // `--wdns` resolves *after* the switch: plain `--wd` keeps the host's
        // vfsmount, so getcwd reports `(unreachable)/…` and direnv bails with
        // "LoadConfig() Getwd failed". Long form needs `=`: `--wdns <dir>`
        // would treat <dir> as the program. Requires util-linux >= 2.39.
        &format!("--wdns={}", dir.display()),
        "--",
        "devenv",
    ])
    .current_dir(dir)
    .env("NEALS_PROJECT", project);
    cmd
}

fn nsenter_devenv(
    dir: &Path,
    project: &str,
    netns_pid: u32,
    devenv_args: &[&str],
    extra_env: &[(&str, &std::ffi::OsStr)],
) -> Result<ExitStatus> {
    let mut cmd = nsenter_command(dir, project, netns_pid);
    cmd.args(devenv_args)
        .stdin(Stdio::inherit())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit());
    for (k, v) in extra_env {
        cmd.env(k, v);
    }
    cmd.status()
        .context("failed to run `nsenter`/`devenv` (is util-linux + devenv on PATH?)")
}

/// Feed `script` to `devenv shell bash` over stdin; output stays inherited.
fn nsenter_devenv_stdin(
    dir: &Path,
    project: &str,
    netns_pid: u32,
    devenv_args: &[&str],
    script: &str,
) -> Result<ExitStatus> {
    use std::io::Write;
    let mut child = nsenter_command(dir, project, netns_pid)
        .args(devenv_args)
        .stdin(Stdio::piped())
        .stdout(Stdio::inherit())
        .stderr(Stdio::inherit())
        .spawn()
        .context("failed to run `nsenter`/`devenv` (is util-linux + devenv on PATH?)")?;
    child
        .stdin
        .take()
        .context("devenv shell has no stdin")?
        .write_all(script.as_bytes())
        .context("failed to write the command into devenv shell stdin")?;
    // Dropping stdin closes the pipe: bash runs the script and exits at EOF.
    child.wait().context("waiting for devenv shell")
}

fn exit_code_from_status(status: ExitStatus) -> ExitCode {
    match status.code() {
        Some(0) => ExitCode::SUCCESS,
        Some(code) => ExitCode::from(u8::try_from(code).unwrap_or(1)),
        None => ExitCode::FAILURE,
    }
}
