[package]
name = "nealsd"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nealsd"
path = "src/main.rs"

[dependencies]
anyhow = "1"
neals-common = { path = "../common" }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "io-util",
    "sync",
    "process",
    "signal",
    "fs",
    "time",
] }

[dev-dependencies]
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "io-util",
    "sync",
    "process",
    "signal",
    "fs",
    "time",
    "test-util",
] }
